task_attributes:
    dialog:
        datasets:
        - visdial
        dataset_size_proportional_sampling: true
        dataset_attributes:
            vqa2:
                data_root_dir: ../data
                image_depth_first: false
                fast_read: false
                image_features:
                    train:
                    - coco/detectron_fix_100/fc6/train_val_2014,coco/resnet152/train_val_2014
                    val:
                    - visdial/detectron_fix_100/fc6/val,visdial/resnet152/val
                    test:
                    - coco/detectron_fix_100/fc6/test2015,coco/resnet152/test2015
                imdb_files:
                    train:
                    - imdb/imdb_visdial_train.npy
                    val:
                    - imdb/imdb_visdial_val.npy
                    test:
                    - imdb/imdb_visdial_test.npy
                max_features: 100
                question_max_len: 14
                vocab_answer: answers_vqa.txt
                vocab_question: vocabulary_visdial.txt
                metrics:
                - r@1
                - r@5
                - r@10
                - mean_r
                - mean_rr
                loss: logit_bce
                return_info: true
training_parameters:
    monitored_metric: visdial_r@1
    metric_minimize: false
