task_attributes:
    vqa:
        datasets:
        - textvqa
        dataset_size_proportional_sampling: true
        dataset_attributes:
            textvqa:
                data_root_dir: ../data
                image_depth_first: false
                fast_read: false
                image_features:
                    train:
                    #- open_images/detectron_fix_100/fc6/train
                    #- open_images/detectron_fix_100/fc6/train,open_images/resnet152/train
                    - open_images/M4C/train,open_images/sbd_ocr_frcn_feature/train #,open_images/sbd_trans_transformer_feature/train
                    - m4c_stvqa_obj_frcn_features/train,m4c_stvqa_ocr_en_frcn_features/train
                    # - open_images/GT_OBJ_FRCN/train
                    val:
                    #- open_images/detectron_fix_100/fc6/train
                    #- open_images/detectron_fix_100/fc6/train,open_images/resnet152/train
                    - open_images/M4C/train,open_images/sbd_ocr_frcn_feature/train #,open_images/sbd_trans_transformer_feature/train
                    # - open_images/GT_OBJ_FRCN/train
                    test:
                    #- open_images/detectron_fix_100/fc6/test
                    #- open_images/detectron_fix_100/fc6/test,open_images/resnet152/test
                    - open_images/M4C/test,open_images/sbd_ocr_frcn_feature/test #,open_images/sbd_trans_transformer_feature/test
                    # - open_images/GT_OBJ_FRCN/test
                imdb_files:
                    train:
                    # - imdb/textvqa_0.5/imdb_textvqa_train.npy
                    # - imdb/m4c_textvqa/imdb_train_ocr_en.npy
                    - imdb/imdb_sbd/0510_train_addObjBox.npy
                    - imdb/m4c_stvqa/imdb_subtrain.npy
                    # - imdb/textvqa_0.5/ye_train.npy
                    # - imdb/imdb_gt/imdb_noempty_train.npy
                    val:
                    # - imdb/textvqa_0.5/imdb_textvqa_val.npy
                    # - imdb/m4c_textvqa/imdb_val_ocr_en.npy
                    - imdb/imdb_sbd/0510_val_addObjBox.npy
                    # - imdb/textvqa_0.5/ye_val.npy
                    # - imdb/imdb_gt/imdb_noempty_val.npy
                    test:
                    # - imdb/textvqa_0.5/imdb_textvqa_test.npy
                    # - imdb/m4c_textvqa/imdb_test_ocr_en.npy
                    - imdb/imdb_sbd/0510_test_addObjBox.npy
                    # - imdb/textvqa_0.5/ye_test.npy
                    # - imdb/imdb_gt/imdb_noempty_test.npy
                features_max_len: 50 # 100
                processors:
                  text_processor:
                    type: bert_tokenizer
                    params:
                      max_length: 20
                      model_data_dir: ../data
                  answer_processor:
                    type: vqa_answer
                    params:
                      vocab_file: vocabs/answers_textvqa_8k.txt
                      preprocessor:
                        type: simple_word
                        params: {}
                      num_answers: 10
                  copy_processor:
                    type: copy
                    params:
                      max_length: 36
                  phoc_processor:
                    type: phoc
                    params:
                      max_length: 50
                  context_processor:
                    type: fasttext
                    params:
                      max_length: 50
                      model_file: .vector_cache/wiki.en.bin
                  ocr_token_processor:
                    type: simple_word
                    params: {}
                  bbox_processor:
                    type: bbox
                    params:
                      max_length: 50
                return_info: true
                # Return OCR information
                use_ocr: true
                # Return spatial information of OCR tokens if present
                use_ocr_info: true
training_parameters:
    monitored_metric: textvqa_vqa_accuracy
    metric_minimize: false
