task_attributes:
  vqa:
    datasets: all
    dataset_size_proportional_sampling: true
    dataset_attributes:
      vqa2:
        data_root_dir: data/
        image_depth_first: false
        image_fast_reader: false
        image_feat_test:
        - detec/detectron/fc6/vqa/test2015
        image_feat_train:
        - detec/detectron/fc6/vqa/train2014
        - detec/detectron/fc6/vqa/val2014
        image_feat_val:
        - detec/detectron/fc6/vqa/val2014
        image_max_loc: 100
        imdb_file_test:
        - imdb/imdb_test2015.npy
        imdb_file_train:
        - imdb/imdb_train2014.npy
        - imdb/imdb_val2train2014.npy
        imdb_file_val:
        - imdb/imdb_minival2014.npy
        question_max_len: 14
        vocab_answer_file: answers_vqa.txt
        vocab_question_file: vocabulary_vqa.txt
        enforce_slow_reader: false
        metrics: vqa_accuracy
        loss: logit_bce
model_attributes:
  top_down_bottom_up:
    model_data_dir: ../data
    classifier:
      type: logit
      params:
        img_hidden_dim: 5000
        text_hidden_dim: 300
    image_embeddings:
    - modal_combine:
        type: non_linear_element_multiply
        params:
          dropout: 0
          hidden_dim: 5000
      normalization: softmax
      transform:
        type: linear
        params:
          out_dim: 1
    image_feature_dim: 2048
    image_feature_encodings:
    - type: finetune_faster_rcnn_fpn_fc7
      params:
        bias_file: detec/detectron/fc6/fc7_b.pkl
        weights_file: detec/detectron/fc6/fc7_w.pkl
    modal_combine:
      type: non_linear_element_multiply
      params:
        dropout: 0
        hidden_dim: 5000
    text_embeddings:
    - type: attention
      params:
        hidden_dim: 1024
        num_layers: 1
        conv1_out: 512
        conv2_out: 2
        dropout: 0
        embedding_dim: 300
        embedding_init_file: vqa2.0_glove.6B.300d.txt.npy
        kernel_size: 1
        padding: 0
optimizer_attributes:
  type: Adamax
  params:
    eps: 1.0e-08
    lr: 0.01
    weight_decay: 0
training_parameters:
  clip_norm_mode: all
  clip_gradients: true
  lr_ratio: 0.1
  lr_steps:
  - 5000
  - 7000
  - 9000
  - 11000
  max_grad_l2_norm: 0.25
  max_iterations: 12000
  log_interval: 100
  snapshot_interval: 1000
  wu_factor: 0.2
  wu_iters: 1000
  patience: 2000
  batch_size: 512
  num_workers: 5
  lr_scheduler: true
  task_size_proportional_sampling: true
  run: train
